# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BlogUser',
        ),
    ]
