# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20170814_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.TextField(auto_created=True, blank=True)),
                ('nickname', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
